"use strict";
const API="https://samuga-news-bot-production.up.railway.app";
let token=localStorage.getItem("samuga-cms-token")||"",me=null,articles=[],editorLang="en",coverType="image",mediaItems=[];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));

document.addEventListener("DOMContentLoaded",()=>{bind();token?boot():showLogin()});
function bind(){
  $("#loginForm").addEventListener("submit",login);$("#logoutBtn").addEventListener("click",logout);$("#themeToggle").addEventListener("click",toggleTheme);$("#mobileSidebar").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"));
  $$(".side-link").forEach(b=>b.addEventListener("click",()=>openView(b.dataset.view)));$$('[data-open-editor]').forEach(b=>b.addEventListener("click",()=>newArticle()));$$('[data-view-jump]').forEach(b=>b.addEventListener("click",()=>openView(b.dataset.viewJump)));
  $$("[data-editor-lang]").forEach(b=>b.addEventListener("click",()=>setEditorLang(b.dataset.editorLang)));$$("[data-cover-type]").forEach(b=>b.addEventListener("click",()=>setCoverType(b.dataset.coverType)));
  $("#coverUrl").addEventListener("input",previewCover);$("#coverUpload").addEventListener("change",uploadCover);$("#videoPosterUrl").addEventListener("input",previewCover);$("#videoPosterUpload").addEventListener("change",uploadVideoPoster);$("#addMediaBtn").addEventListener("click",()=>{mediaItems.push({type:"image",url:"",caption:"",position:""});renderMediaItems()});
  $("#articleForm").addEventListener("submit",e=>{e.preventDefault();saveArticle(false)});$("#saveDraftBtn").addEventListener("click",()=>saveArticle(true));
  $("#articleSearch").addEventListener("input",debounce(loadArticles,300));$("#articleStatus").addEventListener("change",loadArticles);
  $("#newAdBtn").addEventListener("click",()=>openAdDialog());$("#adForm").addEventListener("submit",saveAd);$("#adUpload").addEventListener("change",uploadAdImage);$("#siteSettingsForm").addEventListener("submit",saveSiteSettings);
  $("#newUserBtn").addEventListener("click",()=>openUserDialog());$("#userForm").addEventListener("submit",saveUser);$("#refreshAuditBtn").addEventListener("click",loadAudit);
}
async function api(path,options={}){const headers={...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;if(options.body&&!(options.body instanceof FormData)&&!headers["Content-Type"])headers["Content-Type"]="application/json";const r=await fetch(`${API}${path}`,{...options,headers});let d={};try{d=await r.json()}catch{}if(r.status===401){logout();throw new Error("Session expired")}if(!r.ok||d.ok===false)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function login(e){e.preventDefault();$("#loginError").textContent="";try{const d=await api("/api/admin/login",{method:"POST",body:JSON.stringify({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value})});token=d.token;localStorage.setItem("samuga-cms-token",token);me=d.user;showApp();await loadAll()}catch(err){$("#loginError").textContent=err.message}}
async function boot(){try{const d=await api("/api/admin/me");me=d.user;showApp();await loadAll()}catch{showLogin()}}
function showLogin(){$("#loginScreen").hidden=false;$("#appShell").hidden=true}
function showApp(){$("#loginScreen").hidden=true;$("#appShell").hidden=false;$("#profileName").textContent=me.name||me.email;$("#profileRole").textContent=(me.role||"").replaceAll("_"," ");const admin=["admin","super_admin"].includes(me.role);$$('.admin-only').forEach(x=>x.hidden=!admin);configurePermissions()}
function configurePermissions(){
  const role=me?.role||"contributor",canPublish=["editor","admin","super_admin"].includes(role),canReview=canPublish||role==="journalist";
  const status=$("#articlePublishStatus");
  [...status.options].forEach(o=>{o.hidden=(o.value==="posted"&&!canPublish)||(o.value==="review"&&!canReview);o.disabled=o.hidden});
  $("#sharePanel").hidden=!canPublish;
  $("#articleAuthor").disabled=!canPublish;
  [...$("#userRole").options].forEach(o=>{const restricted=["admin","super_admin"].includes(o.value)&&role!=="super_admin";o.hidden=restricted;o.disabled=restricted});
}
function logout(){token="";me=null;localStorage.removeItem("samuga-cms-token");showLogin()}
function toggleTheme(){const n=document.documentElement.dataset.theme==="light"?"dark":"light";document.documentElement.dataset.theme=n;localStorage.setItem("samuga-theme",n)}
async function loadAll(){await Promise.all([loadArticles(),loadAuthors()]);if(["admin","super_admin"].includes(me.role)){loadUsers();loadAds();loadSiteSettings();loadAudit()}openView("home")}
function openView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$("#viewTitle").textContent=({home:"Overview",articles:"Articles",editor:$("#articleId").value?"Edit article":"New article",ads:"Advertisements",site:"Website",users:"Users",activity:"Activity"})[name]||name;document.querySelector(".sidebar").classList.remove("open")}
async function loadArticles(){try{const q=encodeURIComponent($("#articleSearch")?.value||"");const st=encodeURIComponent($("#articleStatus")?.value||"");const d=await api(`/api/admin/articles?limit=100&q=${q}&status=${st}`);articles=d.articles||[];renderArticles();renderStats()}catch(e){toast(e.message,true)}}
function renderStats(){const published=articles.filter(a=>["posted","published","social_posted"].includes(a.status)).length,drafts=articles.filter(a=>a.status==="draft").length,today=new Date().toISOString().slice(0,10);$("#statPublished").textContent=published;$("#statDrafts").textContent=drafts;$("#statToday").textContent=articles.filter(a=>String(a.updated_at||a.posted_at||"").slice(0,10)===today).length}
function renderArticles(){const head=`<div class="table-row header"><span>Article</span><span>Status</span><span>Category</span><span>Updated</span><span></span></div>`;const rows=articles.map(a=>articleRow(a)).join("")||`<div style="padding:28px;color:var(--muted)">No articles found.</div>`;$("#articleList").innerHTML=head+rows;$("#recentArticles").innerHTML=head+articles.slice(0,6).map(articleRow).join("");$$('[data-edit-article]').forEach(b=>b.addEventListener('click',()=>editArticle(b.dataset.editArticle)));$$('[data-open-article]').forEach(b=>b.addEventListener('click',()=>window.open(`/article?id=${encodeURIComponent(b.dataset.openArticle)}`,'_blank')))}
function articleRow(a){return`<div class="table-row"><div class="article-cell"><strong>${esc(a.title||"Untitled")}</strong><span>${esc(a.author_name||"Samuga Media")}</span></div><span class="status-pill ${esc(a.status)}">${esc(a.status)}</span><span>${esc(a.category||"LOCAL")}</span><span>${esc(shortDate(a.updated_at||a.posted_at))}</span><div class="row-actions"><button data-edit-article="${esc(a.id)}">Edit</button><button data-open-article="${esc(a.id)}">↗</button></div></div>`}
async function editArticle(id){try{const d=await api(`/api/admin/article?id=${encodeURIComponent(id)}`);fillArticle(d.article);openView("editor")}catch(e){toast(e.message,true)}}
function newArticle(){fillArticle({});openView("editor")}
function fillArticle(a){$("#articleForm").reset();$("#articleId").value=a.id||"";$("#articleTitle").value=a.title||"";$("#articleExcerpt").value=a.excerpt||a.summary||"";$("#articleBody").value=a.body||"";$("#articleCategory").value=a.category||"LOCAL";$("#articlePublishStatus").value=a.status||"draft";$("#articleFeatured").checked=!!a.featured;$("#articleBreaking").checked=!!a.breaking;$("#coverCaption").value=a.cover_caption||"";$("#socialCaption").value=a.social_caption||"";editorLang=a.lang||"en";setEditorLang(editorLang);coverType=a.cover_video?"video":"image";setCoverType(coverType);$("#coverUrl").value=a.cover_video||a.cover_image||"";$("#videoPosterUrl").value=a.video_poster||"";mediaItems=Array.isArray(a.media_items)?a.media_items.map(x=>({...x})):[];renderMediaItems();previewCover();if(a.author_id)setTimeout(()=>$("#articleAuthor").value=a.author_id,0);$("#saveState").textContent=a.id?"Loaded":"Not saved"}
function setEditorLang(lang){editorLang=lang;$$('[data-editor-lang]').forEach(b=>b.classList.toggle('active',b.dataset.editorLang===lang));const panel=document.querySelector('.editor-panel');panel.classList.toggle('lang-dv',lang==='dv');$("#articleTitle").dir=lang==='dv'?'rtl':'ltr';$("#articleExcerpt").dir=lang==='dv'?'rtl':'ltr';$("#articleBody").dir=lang==='dv'?'rtl':'ltr'}
function setCoverType(type){coverType=type;$$('[data-cover-type]').forEach(b=>b.classList.toggle('active',b.dataset.coverType===type));$("#coverUpload").accept=type==='video'?'video/mp4,video/webm,video/quicktime':'image/*';$("#videoPosterRow").hidden=type!=="video";previewCover()}
function previewCover(){const url=$("#coverUrl").value.trim(),box=$("#coverPreview");if(!url){box.innerHTML='<span>No cover selected</span>';return}box.innerHTML=coverType==='video'?`<video src="${esc(url)}" poster="${esc($("#videoPosterUrl").value.trim())}" controls playsinline></video>`:`<img src="${esc(url)}" alt="Cover preview">`}
async function uploadFile(file){const fd=new FormData();fd.append('file',file);return api('/api/admin/upload',{method:'POST',body:fd})}
async function uploadCover(){const file=$("#coverUpload").files[0];if(!file)return;$("#uploadProgress").hidden=false;try{const d=await uploadFile(file);$("#coverUrl").value=d.url;coverType=d.type||coverType;setCoverType(coverType);previewCover();toast('Upload complete')}catch(e){toast(e.message,true)}finally{$("#uploadProgress").hidden=true;$("#coverUpload").value=""}}
async function uploadVideoPoster(){const file=$("#videoPosterUpload").files[0];if(!file)return;$("#uploadProgress").hidden=false;try{const d=await uploadFile(file);if(d.type!=="image")throw new Error("Video thumbnail must be an image.");$("#videoPosterUrl").value=d.url;previewCover();toast("Thumbnail uploaded")}catch(e){toast(e.message,true)}finally{$("#uploadProgress").hidden=true;$("#videoPosterUpload").value=""}}
async function uploadAdImage(){const file=$("#adUpload").files[0];if(!file)return;try{const d=await uploadFile(file);if(d.type!=="image")throw new Error("Advertisement banners must be images.");$("#adImage").value=d.url;toast("Banner uploaded")}catch(e){toast(e.message,true)}finally{$("#adUpload").value=""}}
function renderMediaItems(){const list=$("#inlineMediaList");list.innerHTML=mediaItems.map((m,i)=>`<div class="inline-media-item"><input data-media-url="${i}" value="${esc(m.url||'')}" placeholder="Image or video URL"><label class="mini-upload">Upload<input type="file" data-media-upload="${i}" accept="image/*,video/mp4,video/webm,video/quicktime" hidden></label><select data-media-type="${i}"><option value="image" ${m.type==='image'?'selected':''}>Image</option><option value="video" ${m.type==='video'?'selected':''}>Video</option></select><input data-media-position="${i}" type="number" min="1" value="${esc(m.position||'')}" placeholder="After ¶"><button type="button" class="remove-media" data-remove-media="${i}">×</button><input class="media-caption-input" data-media-caption="${i}" value="${esc(m.caption||'')}" placeholder="Caption (optional)"></div>`).join('');$$('[data-remove-media]').forEach(b=>b.addEventListener('click',()=>{mediaItems.splice(+b.dataset.removeMedia,1);renderMediaItems()}));$$('[data-media-url]').forEach(x=>x.addEventListener('input',()=>mediaItems[+x.dataset.mediaUrl].url=x.value));$$('[data-media-type]').forEach(x=>x.addEventListener('change',()=>mediaItems[+x.dataset.mediaType].type=x.value));$$('[data-media-position]').forEach(x=>x.addEventListener('input',()=>mediaItems[+x.dataset.mediaPosition].position=x.value));$$('[data-media-caption]').forEach(x=>x.addEventListener('input',()=>mediaItems[+x.dataset.mediaCaption].caption=x.value));$$('[data-media-upload]').forEach(x=>x.addEventListener('change',async()=>{const file=x.files[0],i=+x.dataset.mediaUpload;if(!file)return;try{const d=await uploadFile(file);mediaItems[i].url=d.url;mediaItems[i].type=d.type;renderMediaItems();toast("Media uploaded")}catch(e){toast(e.message,true)}}))}
async function loadAuthors(){try{const d=await api('/api/admin/authors');const authors=d.authors||[];$("#articleAuthor").innerHTML=authors.map(a=>`<option value="${esc(a.author_id)}">${esc(a.name)} — ${esc(a.role||'Reporter')}</option>`).join('')}catch(e){toast(e.message,true)}}
function articlePayload(forceDraft=false){const status=forceDraft?'draft':$("#articlePublishStatus").value;return{id:$("#articleId").value||null,title:$("#articleTitle").value.trim(),excerpt:$("#articleExcerpt").value.trim(),body:$("#articleBody").value.trim(),lang:editorLang,category:$("#articleCategory").value,status,featured:$("#articleFeatured").checked,breaking:$("#articleBreaking").checked,author_id:$("#articleAuthor").value,cover_image:coverType==='image'?$("#coverUrl").value.trim():null,cover_video:coverType==='video'?$("#coverUrl").value.trim():null,video_poster:coverType==='video'?$("#videoPosterUrl").value.trim():null,cover_caption:$("#coverCaption").value.trim(),media_items:mediaItems.filter(x=>x.url),social_caption:$("#socialCaption").value.trim(),share:{telegram:$("#shareTelegram").checked,facebook:$("#shareFacebook").checked,x:$("#shareX").checked}}}
async function saveArticle(forceDraft){const p=articlePayload(forceDraft);if(!p.title||!p.body){toast('Headline and body are required.',true);return}$("#publishBtn").disabled=true;$("#saveState").textContent='Saving…';try{const d=await api('/api/admin/article',{method:'POST',body:JSON.stringify(p)});$("#articleId").value=d.article.id;$("#saveState").textContent='Saved';toast(d.message||'Article saved');await loadArticles();if(d.share_results){const text=Object.entries(d.share_results).map(([k,v])=>`${k}: ${v.ok?'done':'failed'}`).join(' · ');toast(text,!Object.values(d.share_results).every(x=>x.ok))}}catch(e){$("#saveState").textContent='Save failed';toast(e.message,true)}finally{$("#publishBtn").disabled=false}}

async function loadSiteSettings(){try{const d=await api('/api/admin/site-settings'),s=d.settings||{};$("#siteTaglineEn").value=s.tagline_en||'';$("#siteTaglineDv").value=s.tagline_dv||'';$("#siteCommunityUrl").value=s.community_url||'';$("#siteTipUrl").value=s.tip_url||'';$("#siteContactEmail").value=s.contact_email||'';$("#siteDefaultTheme").value=s.default_theme||'system';$("#siteShowAi").checked=s.show_ai_chat!==false}catch(e){toast(e.message,true)}}
async function saveSiteSettings(e){e.preventDefault();$("#siteSettingsError").textContent='';try{await api('/api/admin/site-settings',{method:'POST',body:JSON.stringify({tagline_en:$("#siteTaglineEn").value.trim(),tagline_dv:$("#siteTaglineDv").value.trim(),community_url:$("#siteCommunityUrl").value.trim(),tip_url:$("#siteTipUrl").value.trim(),contact_email:$("#siteContactEmail").value.trim(),default_theme:$("#siteDefaultTheme").value,show_ai_chat:$("#siteShowAi").checked})});toast('Website settings saved')}catch(err){$("#siteSettingsError").textContent=err.message}}

async function loadAds(){try{const d=await api('/api/admin/ads');renderAds(d.ads||[])}catch(e){toast(e.message,true)}}
function renderAds(ads){const head=`<div class="table-row header"><span>Advertisement</span><span>Status</span><span>Placement</span><span>Fit</span><span></span></div>`;$("#adList").innerHTML=head+(ads.map(a=>`<div class="table-row"><div class="article-cell"><strong>${esc(a.name)}</strong><span>${esc(a.caption||a.destination_url||'')}</span></div><span class="status-pill ${a.active?'posted':'draft'}">${a.active?'Active':'Inactive'}</span><span>${esc(a.placement)}</span><span>${esc(a.fit_mode)}</span><div class="row-actions"><button data-edit-ad="${a.id}">Edit</button></div></div>`).join('')||`<div style="padding:28px;color:var(--muted)">No advertisements yet.</div>`);$$('[data-edit-ad]').forEach(b=>b.addEventListener('click',()=>openAdDialog(ads.find(a=>String(a.id)===b.dataset.editAd))))}
function openAdDialog(a={}){$("#adForm").reset();$("#adId").value=a.id||'';$("#adName").value=a.name||'';$("#adImage").value=a.image_url||'';$("#adMobileImage").value=a.mobile_image_url||'';$("#adLink").value=a.destination_url||'';$("#adCaption").value=a.caption||'';$("#adPlacement").value=a.placement||'feed';$("#adFit").value=a.fit_mode||'contain';$("#adActive").checked=a.active!==false;$("#adDialogTitle").textContent=a.id?'Edit advertisement':'Add advertisement';$("#adDialog").showModal()}
async function saveAd(e){e.preventDefault();try{await api('/api/admin/ads',{method:'POST',body:JSON.stringify({id:$("#adId").value||null,name:$("#adName").value.trim(),image_url:$("#adImage").value.trim(),mobile_image_url:$("#adMobileImage").value.trim(),destination_url:$("#adLink").value.trim(),caption:$("#adCaption").value.trim(),placement:$("#adPlacement").value,fit_mode:$("#adFit").value,active:$("#adActive").checked})});$("#adDialog").close();toast('Advertisement saved');loadAds()}catch(err){$("#adError").textContent=err.message}}


async function loadAudit(){try{const d=await api('/api/admin/audit');renderAudit(d.events||[])}catch(e){toast(e.message,true)}}
function renderAudit(events){const head=`<div class="table-row header audit-row"><span>Action</span><span>User</span><span>Item</span><span>Time</span><span></span></div>`;$("#auditList").innerHTML=head+(events.map(e=>`<div class="table-row audit-row"><div class="article-cell"><strong>${esc(String(e.action||'').replaceAll('_',' '))}</strong><span>${esc(e.entity_type||'system')}</span></div><span>${esc(e.user_email||'System')}</span><span>${esc(e.entity_id||'—')}</span><span>${esc(shortDateTime(e.created_at))}</span><span></span></div>`).join('')||`<div style="padding:28px;color:var(--muted)">No activity recorded yet.</div>`)}

async function loadUsers(){try{const d=await api('/api/admin/users');renderUsers(d.users||[])}catch(e){toast(e.message,true)}}
function renderUsers(users){const head=`<div class="table-row header user-row"><span>Name</span><span>Email</span><span>Role</span><span>Status</span><span></span></div>`;$("#userList").innerHTML=head+users.map(u=>`<div class="table-row user-row"><div class="article-cell"><strong>${esc(u.name)}</strong><span>Last login: ${esc(shortDate(u.last_login))}</span></div><span>${esc(u.email)}</span><span>${esc(u.role.replace('_',' '))}</span><span class="status-pill ${u.active?'posted':'draft'}">${u.active?'Active':'Disabled'}</span><div class="row-actions"><button data-edit-user="${u.id}">Edit</button></div></div>`).join('');$$('[data-edit-user]').forEach(b=>b.addEventListener('click',()=>openUserDialog(users.find(u=>String(u.id)===b.dataset.editUser))))}
function openUserDialog(u={}){$("#userForm").reset();$("#userId").value=u.id||'';$("#userName").value=u.name||'';$("#userEmail").value=u.email||'';$("#userRole").value=u.role||'journalist';$("#userActive").checked=u.active!==false;$("#userPassword").required=!u.id;$("#userDialogTitle").textContent=u.id?'Edit user':'Add user';$("#userDialog").showModal()}
async function saveUser(e){e.preventDefault();try{await api('/api/admin/users',{method:'POST',body:JSON.stringify({id:$("#userId").value||null,name:$("#userName").value.trim(),email:$("#userEmail").value.trim(),role:$("#userRole").value,password:$("#userPassword").value,active:$("#userActive").checked})});$("#userDialog").close();toast('User saved');loadUsers()}catch(err){$("#userError").textContent=err.message}}
function shortDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'2-digit'})}
function shortDateTime(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function toast(message,error=false){const t=$("#toast");t.textContent=message;t.style.background=error?'var(--danger)':'var(--text)';t.style.color=error?'white':'var(--bg)';t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3500)}
function debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}}
