"use strict";
const API="https://samuga-news-bot-production.up.railway.app";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const attr=s=>esc(s).replace(/`/g,"&#096;");
const id=new URLSearchParams(location.search).get("id")||"";
document.addEventListener("DOMContentLoaded",()=>{setupTheme();loadSettings();loadArticle();window.addEventListener("scroll",updateProgress,{passive:true})});
function setupTheme(){document.querySelector("#themeToggle")?.addEventListener("click",()=>{const n=document.documentElement.dataset.theme==="light"?"dark":"light";document.documentElement.dataset.theme=n;localStorage.setItem("samuga-theme",n)})}

async function loadSettings(){try{const r=await fetch(`${API}/api/site-settings`,{cache:"no-store"});const d=await r.json(),s=d?.settings||{};if(s.community_url)document.querySelector("#articleCommunity")?.setAttribute("href",s.community_url);if(!localStorage.getItem("samuga-theme")&&["light","dark"].includes(s.default_theme))document.documentElement.dataset.theme=s.default_theme}catch{}}

function updateProgress(){const total=document.documentElement.scrollHeight-innerHeight;document.querySelector("#readingBar").style.width=(total>0?Math.min(100,scrollY/total*100):0)+"%"}
async function loadArticle(){try{const r=await fetch(`${API}/api/article?id=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||"Article unavailable");render(d)}catch(e){document.querySelector("#articleRoot").innerHTML=`<div class="policy-main"><h1>Article unavailable</h1><p>${esc(e.message)}</p><p><a href="/">Return to latest stories →</a></p></div>`}}
function render(d){const dv=d.lang==="dv"||/[ހ-޿]/.test(`${d.title||""} ${d.body||""}`);document.documentElement.lang=dv?"dv":"en";document.documentElement.dir=dv?"rtl":"ltr";document.body.classList.toggle("lang-dv",dv);document.title=`${d.title} | Samuga Media`;const share=`${location.origin}/article?id=${encodeURIComponent(d.id)}`;document.querySelector("#articleRoot").innerHTML=articleMarkup(d,share);document.querySelector("#copyBtn")?.addEventListener("click",async e=>{await navigator.clipboard.writeText(share);e.currentTarget.textContent="Copied"})}
function articleMarkup(d,url){const cover=d.cover_video?`<div class="article-cover"><video src="${attr(d.cover_video)}" poster="${attr(d.video_poster||d.cover_image||"")}" controls playsinline preload="metadata"></video>${d.cover_caption?`<p class="media-caption">${esc(d.cover_caption)}</p>`:""}</div>`:d.cover_image?`<div class="article-cover"><img src="${attr(d.cover_image)}" alt="${esc(d.cover_caption||d.title||"")}">${d.cover_caption?`<p class="media-caption">${esc(d.cover_caption)}</p>`:""}</div>`:"";const a=d.author||{};const avatar=a.photo?`<img src="${attr(a.photo)}" alt="${esc(a.name||"Samuga Media")}">`:`<span class="byline-avatar">S</span>`;const updated=d.updated_at&&d.updated_at!==d.published_at?`<span class="updated-note">Updated ${esc(formatDate(d.updated_at))}</span>`:"";return`<div class="article-container"><article dir="${d.lang==="dv"?"rtl":"ltr"}"><div class="article-kicker"><strong>${esc(d.category||"Local")}</strong><span>${d.breaking?"Live · ":""}Samuga Media</span></div><h1 class="article-headline">${esc(d.title)}</h1>${d.excerpt?`<p class="article-subhead">${esc(d.excerpt)}</p>`:""}<div class="byline" dir="ltr">${avatar}<div class="byline-details"><strong>${esc(a.name||"Samuga Media")}</strong><span>${esc(a.role||"Newsroom")}</span></div><div class="byline-time"><time>${esc(formatDate(d.published_at||d.time))}</time>${d.reading_time?`<br>${esc(d.reading_time)} min read`:""}${updated}</div></div>${cover}<div class="article-body">${bodyWithMedia(d)}</div><div class="share-row" dir="ltr"><strong>Share</strong><a class="share-btn" target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}">Facebook</a><a class="share-btn" target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?text=${encodeURIComponent(d.title)}&url=${encodeURIComponent(url)}">X</a><a class="share-btn" target="_blank" rel="noopener" href="https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(d.title)}">Telegram</a><button class="share-btn" id="copyBtn">Copy link</button></div>${relatedMarkup(d.related||[])}</article></div>${footerMarkup()}`}
function bodyWithMedia(d){const paras=(Array.isArray(d.paragraphs)&&d.paragraphs.length?d.paragraphs:String(d.body||"").split(/\n\s*\n+/)).filter(Boolean);const media=Array.isArray(d.media_items)?d.media_items:[];let out="";paras.forEach((p,i)=>{out+=`<p>${esc(p)}</p>`;media.filter(m=>Number(m.position||0)===i+1).forEach(m=>out+=mediaMarkup(m))});media.filter(m=>!m.position||Number(m.position)>paras.length).forEach(m=>out+=mediaMarkup(m));return out||`<p>${esc(d.excerpt||d.title||"")}</p>`}
function mediaMarkup(m){if(!m?.url)return"";const visual=m.type==="video"?`<video src="${attr(m.url)}" poster="${attr(m.poster||"")}" controls playsinline preload="metadata"></video>`:`<img src="${attr(m.url)}" alt="${esc(m.caption||"")}" loading="lazy">`;return`<figure class="article-media">${visual}${m.caption?`<figcaption class="media-caption">${esc(m.caption)}</figcaption>`:""}</figure>`}
function relatedMarkup(items){if(!items.length)return"";return`<section class="related"><h2>More from Samuga</h2><div class="related-grid">${items.slice(0,4).map(x=>`<a class="related-card" href="/article?id=${encodeURIComponent(x.id)}"><small>${esc(x.category||"Latest")}</small><h3>${esc(x.title)}</h3></a>`).join("")}</div></section>`}
function footerMarkup(){return`<footer class="site-footer" style="margin-top:70px"><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Samuga Media. All rights reserved.</span><span>Powered by <a href="https://www.samugacreative.com" target="_blank" rel="noopener">Samuga Creative</a></span></div></footer>`}
function formatDate(v){if(!v)return"Recent";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("en-MV",{dateStyle:"medium",timeStyle:"short"})}
